apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: location-api
  name: location-api
spec:
  type: NodePort
  ports:
  - name: headless
    port: 8081
  selector:
    io.kompose.service: location-api
status:
  loadBalancer: {}

